#!/usr/bin/env python
# coding: utf-8



import pandas as pd

x = [10,12,14]
y = [1600,1920,2240]

df =pd.DataFrame ({"Restaurant_$" : x,
      "Restaurant_Dzd" : y})
df

dfa = df.drop("Restaurant_Dzd",axis = 1)
dfd

dfb = df.drop("Restaurant_$",axis = 1)
dfb

mdfa = dfa.mean()
vdfa = dfa.var()
sdfa = dfa.std()
cvdfa = (sdfa/mdfa)*100

mdfb = dfb.mean()
vdfb = dfb.var()
sdfb = dfb.std()
cvdfb = (sdfb/mdfb)*100
cvdfb
